spring.application.name=jounaling_app

# -------- Database configuration
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017

spring.data.mongodb.uri=mongodb+srv://paraspalli1234_db_user:VBqpQ4in458BimoO@journal.yujct7q.mongodb.net

spring.data.mongodb.database=journaling_db
spring.data.mongodb.auto-index-creation=true

# spring.data.mongodb.username=paraspalli1234_db_user
# spring.data.mongodb.password=VBqpQ4in458BimoO

# -------- Spring Security configuration
spring.security.user.name=admin
spring.security.user.password=admin123