spring.application.name=jounaling_app

# -------- Database configuration
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017

spring.data.mongodb.uri=mongodb+srv://paraspalli1234_db_user:VBqpQ4in458BimoO@journal.yujct7q.mongodb.net/?appName=Journal


spring.data.mongodb.database=journaling_db
spring.data.mongodb.auto-index-creation=true

# spring.data.mongodb.username=paraspalli1234_db_user
# spring.data.mongodb.password=VBqpQ4in458BimoO

# -------- Spring Security configuration
spring.security.user.name=admin
spring.security.user.password=admin123

# -------- Server configuration
server.port=8081
server.servlet.context-path=/api/v1


# -------- Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=paraspalli01@gmail.com
spring.mail.password=xxxxxxxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# -------- redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379


# -------- Kafka configuration
# # Kafka Broker
# spring.kafka.bootstrap-servers=kafka-1b669479-paraspalli1234-5af0.k.aivencloud.com:19895

# # SSL Configuration (Aiven)
# spring.kafka.properties.security.protocol=SSL
# spring.kafka.properties.ssl.truststore.type=PEM
# spring.kafka.properties.ssl.keystore.type=PEM

# spring.kafka.properties.ssl.truststore.certificates=classpath:certs/svc.pem
# spring.kafka.properties.ssl.keystore.certificate.chain=classpath:certs/service.cert
# spring.kafka.properties.ssl.keystore.key=classpath:certs/service.key
# spring.kafka.properties.session.timeout.ms=45000

# # Consumer
# spring.kafka.consumer.group-id=cron-group
# spring.kafka.consumer.auto-offset-reset=earliest
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# # Producer
# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# #
# spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.jounaling_app.JounalingAppApplication


# spring.kafka.bootstrap-servers=kafka-1b669479-paraspalli1234-5af0.k.aivencloud.com:19895

# spring.kafka.properties.security.protocol=SSL
# spring.kafka.properties.ssl.keystore.type=PEM
# spring.kafka.properties.ssl.truststore.type=PEM

# spring.kafka.properties.ssl.truststore.location=classpath:certs/ca.pem
# spring.kafka.properties.ssl.keystore.location=classpath:certs/service.key
# spring.kafka.properties.ssl.keystore.certificate.chain=classpath:certs/service.cert
# spring.kafka.properties.ssl.keystore.key=classpath:certs/service.key

# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# spring.kafka.consumer.group-id=corn-group
# spring.kafka.consumer.auto-offset-reset=earliest
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# spring.kafka.consumer.properties.spring.json.trusted.packages=*


###

spring.kafka.bootstrap-servers=kafka-1b669479-paraspalli1234-5af0.k.aivencloud.com:19895

# SSL Protocol & Types
spring.kafka.properties.security.protocol=SSL
spring.kafka.properties.ssl.keystore.type=PEM
spring.kafka.properties.ssl.truststore.type=PEM

# Truststore (CA Certificate)
spring.kafka.properties.ssl.truststore.location=-----BEGIN CERTIFICATE-----
MIIERDCCAqygAwIBAgIUQT7BEiHjJW49/pWFPheGGhiVWBMwDQYJKoZIhvcNAQEM
BQAwOjE4MDYGA1UEAwwvYWU3NDYzZTUtZDQ0ZC00YjgwLWJlZmQtOGEzMzVhOWJm
NTYzIFByb2plY3QgQ0EwHhcNMjYwNDI5MDMxODQ1WhcNMzYwNDI2MDMxODQ1WjA6
MTgwNgYDVQQDDC9hZTc0NjNlNS1kNDRkLTRiODAtYmVmZC04YTMzNWE5YmY1NjMg
UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAJnP+fFq
nbxygH2P0PXBcULymalCU2jYO4eVYXlV5P7R5HiDznQXDjhrbU8Jy0lpKJDs3qqT
0vtFRT40ZAzwJEUaMJEQJO7FdUS0C1VVkMcROGYSwbzBjsh3O5Ah7p99V+J59kRA
bjQN4dj4h6UhLokhhPqDv1cy3P+sYpSRR/b+OcNvLEdWG0WPYt67n8hEzXQN1LzB
7BVvsW/CedrO/Dq0bvde61Rm2c/qd1S3Ift2q7tR7YmOJncMTTeNaEMlmX2EehFK
ez1Cq73XFO5krbe70CoEpeOIFuMs9F77YV1qOeHvh0kgOJSy0ujZvemiFHcMQqYL
mZlgCZ6WIJ4j1AxKcdiJKIIb72s729cbDpQHJjoHQtO0YtgpTJmwcIMSWRFdcVf+
V7FXp1vgaxJz2mXztIaRfVehbiWG24RxWYGf/JER9KIB0un/u4OxSFa6uSDgGow8
tO1p+nNVeJHv1+y53OkEw1kYXOKN8veT3gDp8dP5dswiOEWcjiD9Q74fawIDAQAB
o0IwQDAdBgNVHQ4EFgQUK/iCwBI1ZMGiZRuGA5coRZ0aIeEwEgYDVR0TAQH/BAgw
BgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBACFWqZxbkvZK
UVz3e9q2deWPONhTCtAk4ypc5tOdljH4I0K0BgDglHS6Gh1bylnoWJGyIzXhacYl
P8fG8YMFNMALjGoW27258PKnV1J6JkwxcEvyjcSQ0MTY0O64W1JbmgLEF7xkscDw
gVnp240Ysh4Q22SFPkstPHE1rGV0lrtTKIo7gj3mQfOZQc2WwMw5EMx5DTpkXffh
R/VvAKoL8ccOX02ujix7kU1fekhHs3evpxWg2Js2sA1j0u3lw0sYgk3FckbRrIks
UnbR/uSkHvHloz6eeRMxqBndQUB8BhxkpRZG8+vku8Mmw7GNauRX2pXLM2VVfITY
k/nYU+xq3ikyval0glrGk2Zgxpb3NlqvlGNVs/QtCW/fbtx7zRxbaEo4AVmZ89mv
M6RmF3W1OfstUpSFBGfFrZrIRVBt07R6W3KB8Bj3cmBoQ/qRGfxHCjafutSq72u/
XimrBVmrskosPCL3wCUgL/Bp77H2veDi8bb4PsLskg6FdQOw+YA98g==
-----END CERTIFICATE-----


# Keystore (Service Key and Certificate)
# REMOVED: .keystore.location and .keystore.key.location
spring.kafka.properties.ssl.keystore.certificate.chain=-----BEGIN CERTIFICATE-----
MIIEYTCCAsmgAwIBAgIUQ3UpYqw1brKn+L13GVQfDoyv4sQwDQYJKoZIhvcNAQEM
BQAwOjE4MDYGA1UEAwwvYWU3NDYzZTUtZDQ0ZC00YjgwLWJlZmQtOGEzMzVhOWJm
NTYzIFByb2plY3QgQ0EwHhcNMjYwNDI5MDMyMDI3WhcNMjgwNzI3MDMyMDI3WjA/
MRcwFQYDVQQKDA5rYWZrYS0xYjY2OTQ3OTERMA8GA1UECwwIdTFrM2I3djUxETAP
BgNVBAMMCGF2bmFkbWluMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA
lkAIfLi7Q8We15hCYIWJ8JXFcjqGLKD6kTqAbGOrS+dbZlU0YQwA2AAeV08ja7r1
6r4JDuMC9RTYZvf3oCTV+u30zaWua7DSf6vjWk6t7Da99XcLgIj2nKDn7QkBZOe1
xh0Y2nw3f8dR/XM2EJDMb7PonC1a2+OScSDHutwfBWZTOoNjzYEHBi04Drlhx/Xf
/A8WR4RYXAD5fcjbjw83ro+tUQ31RNgLFfwzathN7kPGnrEsUD9GEyiXBclNEfOV
6cTyZ8sG6dhzBcHQMaXmbdT8XX7DhC5Hz7OQawk8azWk2LFc85WlOQaTJMbQAkj+
XcDi2s7znhMgSCzsaQPukDcUgbVritIXKJ1wqfx+9ghR2r7aFeSXwb0DJL7xH9sF
dpUL3rHA8shdFXnwZ7OUO5wAE/o+2B3ErMqJOWXnpdXvnpg8dTjsLGq81D0lVQZc
bjCzOg23VId8G2M5kOQ/YrZgP8UBSqX4KYIpk/RPGgUqiQPGCiewigpTyhzGv8TB
AgMBAAGjWjBYMB0GA1UdDgQWBBRMtOqXO6AkxF2vcQFDY2NetIV4DzAJBgNVHRME
AjAAMAsGA1UdDwQEAwIFoDAfBgNVHSMEGDAWgBQr+ILAEjVkwaJlG4YDlyhFnRoh
4TANBgkqhkiG9w0BAQwFAAOCAYEAYacqtdbjy4ZP8UKBmd0yD129BRtYTK6be8yc
ngPcIW5vnxBSbPcUs1NW5M1Wy/9HtrtcGn3ae1dB2SJA7W5d5icddABKASB+ayGW
2bH7KPjVcFUJNdIba17/hMS7Dc79e2z9ONOHusTW3NVUTssk9LpC+ob8fOy5cpuu
XmBBdCpJ8gv3+Ayk6FaugoBkrYTrgwtsiKGV5SqaKfeZ8bsFuQNSCzOAOQ/jvOre
gRe5CpVxQQmNQMZ/gtA4XRECNc49MR0U/HVNWQOPauCu+Et6f1LE/lP3YSlOsU8J
2cjsRF0ahaQZ1CqK0rv0zlDKeIyofbwZIQrmthSJrUPUILL+MJPVFhJifMfuimow
QKJi2p0Ks0ohBDeRfMBAWO4DeG0g/ymHqj1cK/KQPT8BuceqPt+38ZJ1u7GT92WS
vnuCZOk/gI8QRY8Qx+VDhzBNgyaxnrQqoL766A/XwjpWAbNvLn8feulfQUatXhvD
J/0dRMWqx7C9FLCOD02+Nyy+StOX
-----END CERTIFICATE-----

spring.kafka.properties.ssl.keystore.key=-----BEGIN PRIVATE KEY-----
MIIG/AIBADANBgkqhkiG9w0BAQEFAASCBuYwggbiAgEAAoIBgQCWQAh8uLtDxZ7X
mEJghYnwlcVyOoYsoPqROoBsY6tL51tmVTRhDADYAB5XTyNruvXqvgkO4wL1FNhm
9/egJNX67fTNpa5rsNJ/q+NaTq3sNr31dwuAiPacoOftCQFk57XGHRjafDd/x1H9
czYQkMxvs+icLVrb45JxIMe63B8FZlM6g2PNgQcGLTgOuWHH9d/8DxZHhFhcAPl9
yNuPDzeuj61RDfVE2AsV/DNq2E3uQ8aesSxQP0YTKJcFyU0R85XpxPJnywbp2HMF
wdAxpeZt1PxdfsOELkfPs5BrCTxrNaTYsVzzlaU5BpMkxtACSP5dwOLazvOeEyBI
LOxpA+6QNxSBtWuK0hconXCp/H72CFHavtoV5JfBvQMkvvEf2wV2lQvescDyyF0V
efBns5Q7nAAT+j7YHcSsyok5Zeel1e+emDx1OOwsarzUPSVVBlxuMLM6DbdUh3wb
YzmQ5D9itmA/xQFKpfgpgimT9E8aBSqJA8YKJ7CKClPKHMa/xMECAwEAAQKCAYAB
AJrbwcA1aGM4cgW2JDxTkLagLxRVtQ1swKQcdQEqZh5hbk7a1RbiaxWmmdRGP6Ho
Q3y6FT91Uc+QpPWevO+jyFVzcZG8iVpN4vntXUo+YcwcVEN35bQnFD/tt9CtyFaM
wmuzk3HN8PFBvI4L9uDvEtc9AxfZO5hISxfXWr4V54USMOmSydow9fDmroM6Xm4S
dVSTPJm1ksFbnK76be7gezxVrz8aqNKmPmpNEOTJ744M6eBPSgJf64MvnZzukDXb
hdVORSK7/OSs/wEqEdMeNpzg7uSQn2562l0uKyhVyJVhjVDz7W9lByqM83rd9kKm
JDHJCXWyk0kd0fZSkSHry5SFKW2M8v1UAUky0U+1Z7HyRJbE4FMGH6zNLA+anXbT
FreGvd3ctZpdNJw0RHp3c7j09f+Vrd9xcgARLPQPVxzB9BtxtQURzUyk6ExWOGC4
ls6m6OEHuSy/hWIPmv6i9AeDc6rq+odR61SwT0m6kzKDE0esc5yAdrFHBIgzj5EC
gcEAxKDTjQePpSFSZxe3j/fEaW0Z19KebaQRP9XirkVNcIrKoZr/8Q5a8oKQkRZG
cyQ8hCtsiFGE/gnvAlc1RTvLERlQgv1XJjy27XkHdqwgb/0yTE/UYNDWPNz7UDP6
Mm2yfW/Qne8CHWhC2KpUc4n/Oj7Tvoz0O7PWELr1kTnl0o/k0t80L5GO/bScSxBB
xrKANtfm0hcvS7wOhCI48l+ZePjIFZgpA1OGbm22gP7WHxvK1toMA/ybFXj7+OOR
m9u5AoHBAMOeOWVzD7b+Oyjv7uEjQRiPGZpFLpL5ouwAXHAlqi0Aavv2Aqhid6VO
KhHrhx/M36voPUii9qGRcECHYHcoPVdC0fRivgg0Iku0SolZwuHZ48lWBzOGSLAd
1lN3jIrYAyU2AfHin/iTcGRjSC26vgXZfmoBQ+P/zYlY9vdBEyuTqgJr3yF61sXc
1RZb4+MBSYX0xulsXSc6p6rUxPsTfatdCrGyDx/rITQHW8GdPbo5tI3bBfoihf9g
+/Fh8t+FSQKBwGvlPHC053PbdxYvA4EymkqnnXi6kEjlsLlwqnSqfrX00wAex7cF
A47zalTS/lGMXtC/60xaPzoPRWHpbMfS6bk2ROG8FqhaxJ5GvXu3NA1/yKvrWkTO
E+FN+XGnM/GcFEeUpcskLerpHVU7EiBcZvsVIqf7PMHOCvcfQEUymhQS9aNo63/2
xZoeE211PELGDGkLzBMYudE7HlQPW2RUZSjmixSebFLw8GGEPpNGQ0TKwWFoQROm
94qu2sVWSr5VsQKBwHFpjoVOzFGf29TEJo7IzbjbXlCew33a1aZWH0G11I/6qgwi
eS/+xrdENgflsZWyRgt4ve8a7DqIA7ilxDvRTJ8G0osJpHtFHo0dngk7zUz78qCM
C+jHdeUFp3kE2qq0yj4Mrdv7NBv9/y90kChTGFBz5GK5EQ9jA1saBTUcuWyOVAbL
W7YhbduRSMmJxPmbiXDslVZHyUoxK3xTl1Cp4DY13zlern4m6D0t9vitnVgWlKOZ
1EFNOrrxE6DC1PjaYQKBwAVEgzdL+5uv4P4l0gJhOI727QhobcU36Y3+Rz7skml+
0P2Aa3bKiiA/s420N9MzEnY62cJaLXJGqqb4r1u7EWUn3zs5/fAf1efaU3ygu0bA
z96RZktX5BveQgJ+xfWdTTw7W0I44eEOaasMdc3bTDpKsfxMvd0uALyA/nUWfZTe
dxDm/RVghWH2TlCsBO9ODDvWAQx8JVKN6bVtB+K9WlwzNuxAb1au0NlN7U2Mc/XX
e6i6Q5rx5zUG7etmCGvO5Q==
-----END PRIVATE KEY-----


# Producer Configs
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer Configs
spring.kafka.consumer.group-id=corn-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
