spring.application.name=jounaling_app

# Database configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaling_db

# spring.data.mongodb.username=your_username
# spring.data.mongodb.password=your_password