spring.application.name=jounaling_app

# -------- Database configuration
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017

spring.data.mongodb.uri=mongodb+srv://paraspalli1234_db_user:VBqpQ4in458BimoO@journal.yujct7q.mongodb.net

spring.data.mongodb.database=journaling_db
spring.data.mongodb.auto-index-creation=true

# spring.data.mongodb.username=paraspalli1234_db_user
# spring.data.mongodb.password=VBqpQ4in458BimoO

# -------- Spring Security configuration
spring.security.user.name=admin
spring.security.user.password=admin123

# -------- Server configuration
server.port=8080
server.servlet.context-path=/api/v1

# -------- Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=paraspalli01@gmail.com
spring.mail.password=xxxxxxxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# -------- redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379